sudo: false

language: php

php:
  - 7.1
  - 7.2.2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE laravel_reviews;'

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_FLAGS=""
    - DB_HOST=127.0.0.1
    - DB_DATABASE=laravel_reviews
    - DB_USERNAME=travis
    - DB_PASSWORD=
    - DB_UNIX_SOCKET=~travis/.my.cnf

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
